info:
  app:
    name: CPF
    description: CPF

spring:
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: local
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  flyway:
    enabled: false

logging:
  file:
    max-size: 10MB
    max-history: 2
  pattern:
    dateformat: dd/MM/yyyy HH:mm:ss.SSS
  level:
    org:
      springframework=INFO:

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
  health:
    mail:
      enabled: false

springfox:
  documentation:
    auto-startup: false